
@startuml
mainframe **act** Gerenciar Eventos
' !pragma useVerticalIf on
start
- Acessar Gerenciar Eventos
- Listar Eventos
- Escolher Opcao
if (Cadastrar) then (sim)
  :Text 1;
(nao) elseif (Alterar) then (yes)
  :Text 2;
(nao) elseif (Remover) then (yes)
  :Text 3;
(nao) elseif (Ver detalhes) then (yes)
  :Text 4;
else (nothing)

endif
stop
@enduml


(*) --> "Acessar Gerenciar Eventos"
--> "Listar Eventos"
if "Cadastrar Evento?" then
  -->[sim] "Selecionar Cadastrar Evento"
  -->"Informar Dados do Evento"
  -->"Informar Localidade do Evento"
  -->"Buscar Coordenadas"
  -->if "Os Dados Sao Validos?" then
    -->[sim]"Criar Evento"
    -->(*)
  else
    -->[nao]"Informar Dados do Evento"
  endif
else
  -->[nao] if "Alterar Evento?" then
    -->[sim] "Selecionar Alterar Evento"
  --> "Informar Dados Necessários do Evento"
  --> if "Informou Localidade?" then
    -->[sim] "Buscar Coordenadas "
    -->"Enviar Formulario"
  else
    --> [nao] "Enviar Formulario"
    -->if "Os Dados Sao Validos?" then
    -->[sim] "Atualizar Evento"
    --> (*)
    else
    -->[nao] "Informar Dados Necessários do Evento"
    endif
  endif
  else
    -->[nao] if "Remover Evento?" then
      -->[sim]"Selecionar Evento a Ser Removido"
      --> if "Confirma remocao?" then
        -->[sim](*)
      else
        -->[nao]"Selecionar Evento a Ser Removido"
      endif
      else
    -->[nao] if "Detalhes do Evento?" then
    -->[sim]"Ir Para Detalhes do Evento"
    -->(*)
    else
      -->[nao]"Listar Eventos"
    endif
    endif
  else
endif