@startuml

skinparam classAttributeIconSize 0
hide circle

class Usuario {
  -id: Integer
  -auth_key: String
  -auth_method: String
  -email: String
  -status: String
  +list(): Usuario[]
  +show(id: Integer): Perfil
  +login(): void
  +logout(): void
}

class Administrador {
  +deliberarDenuncia(status: String): void
  +promoverUsuario(usuario_id: Integer): void
  +suspenderUsuario(usuario_id: Integer): void
  +excluirEvento(evento_id: Integer): void
}

class Perfil {
  -usuario_id: Integer
  -nome: String
  -foto: String
  -twitter_usuario: String
  -facebook_usuario: String
  -instagram_usuario: String
  +show(id: Integer): Perfil
  +update(usuario_id: Integer, payload: Perfil): void
}

class Denuncia {
  -id: Integer
  -categoria: Integer
  -data: Datetime
  -status: String
  -autor_id: Integer
  -denunciado_id: Integer
  +list(): Denuncia[]
  +show(id: Integer): Denuncia
  +create(payload: Denuncia): void
}

class Evento {
  -id: Integer
  -titulo: String
  -data_hora: Datetime
  -categoria: Integer
  -status: String
  -data_criacao: Datetime
  -autor_id: Integer
  -imagens: Imagem[]
  -lat: Float
  -lng: Float
  +list(): Evento[]
  +show(id: Integer): Evento
  +create(payload: Evento): void
  +update(_id: Integer, payload: Evento): void
  +delete(_id: Integer): void
}

class Participacao {
  -evento_id: Integer
  -usuario_id: Integer
  -data_criacao: Datetime
  +getData_criacao(): void
  +create(evento_id: Integer, usuario_id: Integer): void
  +delete(evento_id: Integer, usuario_id: Integer): void
}

class Imagem {
  -id: Integer
  -url: String
  -Evento_id: Integer
  +getUrl(): void
  +create(payload: Imagem): void
  +delete(_id: Integer)
  +list(evento_id: Integer): Imagem[]
}

class Mensagem {
  -id: Integer
  -conteudo: String
  -autorId: Integer
  -eventoId: Integer
  -referenciaId: Integer
  +list(evento_id: Integer): void
  +create(payload: Evento): void
}

Usuario "1" *-- "1" Perfil
Usuario "1" <|-- Administrador

Evento "1" -- "0..*" Imagem
Evento "0..*" -- "1" Usuario

Participacao "0..*" -- "1" Usuario
Evento "1" -- "0..*" Participacao

Usuario "1" -- "0..*" Denuncia
Usuario "1" -- "0..*" Denuncia

Mensagem "0..*" -- "1" Evento
Mensagem "0..*" -- "1" Usuario
Mensagem "0..1" -- "0..1" Mensagem

@enduml